# Image for Terraform development
# Based on the official image available at https://hub.docker.com/r/hashicorp/terraform

# hadolint ignore=DL3007
FROM docker.io/hashicorp/terraform:latest

ENV TF_LS_VERSION=0.32.4
RUN wget -q https://releases.hashicorp.com/terraform-ls/${TF_LS_VERSION}/terraform-ls_${TF_LS_VERSION}_linux_amd64.zip -O tfls.zip && \
    unzip tfls.zip && \
    mv terraform-ls /usr/local/bin/terraform-ls && \
    chmod +x /usr/local/bin/terraform-ls && \
    rm tfls.zip
