# Image for Clojure development
# Based on the official image available at https://hub.docker.com/_/clojure

FROM docker.io/library/clojure:latest

# TODO: install https://github.com/clojure-lsp/clojure-lsp
