# Image for Clojure development
# Based on the official image available at https://hub.docker.com/_/clojure

FROM docker.io/library/clojure:latest

RUN apt-get update && \
    apt-get install --assume-yes curl && \
    rm -rf /var/lib/apt/lists/* && \
    curl -O https://raw.githubusercontent.com/clojure-lsp/clojure-lsp/master/install && \
    chmod 0755 ./install && \
    ./install && \
    apt-get purge --assume-yes --auto-remove curl
