# Image for Clojure development
# Based on the official image available at https://hub.docker.com/_/clojure

FROM docker.io/library/clojure:latest

RUN apt-get update && \
    apt-get install --assume-yes curl && \
    rm -rf /var/lib/apt/lists/*
RUN curl https://raw.githubusercontent.com/clojure-lsp/clojure-lsp/master/install --output install-clojure-lsp.sh && \
    chmod +x ./install-clojure-lsp.sh && \
    ./install-clojure-lsp.sh
RUN apt-get purge --assume-yes --auto-remove curl
