# Image for Nix development
# Based on the official image available at https://hub.docker.com/r/nixos/nix

FROM docker.io/nixos/nix:latest

RUN nix-env -i -f https://github.com/nix-community/rnix-lsp/archive/master.tar.gz
