# Image for Python development
# Based on the official image available at https://hub.docker.com/_/python

# hadolint ignore=DL3007
FROM docker.io/library/python:latest

RUN pip install python-lsp-server
