# Image for Python development
# Based on the official image available at https://hub.docker.com/_/python

FROM docker.io/library/python:latest

# TODO: install https://github.com/python-lsp/python-lsp-server
