# Image for Elixir development
# Based on the official image available at https://hub.docker.com/_/elixir

# hadolint ignore=DL3007
FROM docker.io/library/elixir:latest

ENV ELIXIR_LS_VERSION=0.12.0
RUN wget https://github.com/elixir-lsp/elixir-ls/releases/download/v${ELIXIR_LS_VERSION}/elixir-ls.zip -O elixir-ls.zip && \
    mkdir --parents /opt/elixir/ls && \
    unzip elixir-ls.zip -d /opt/elixir/ls
