# Image for Nim development
# Based on the official image available at https://hub.docker.com/r/nimlang/nim

FROM docker.io/nimlang/nim:latest

# TODO: requires https://github.com/nim-lang/Nim/issues/19604
RUN nimble refresh
RUN nimble install -y nimlsp
