# Image for Nim development
# Based on the official image available at https://hub.docker.com/r/nimlang/nim

# hadolint ignore=DL3007
FROM docker.io/nimlang/nim:latest

RUN nimble refresh
RUN nimble install -y nimlsp
