# Image for Java development with Maven
# Based on the official image available at https://hub.docker.com/_/maven

FROM docker.io/library/maven:latest

# Install Java language server
ENV JDTLS_VERSION=1.25.0
ENV JDTLS_TIMESTAMP=202306291518
RUN curl -L https://download.eclipse.org/jdtls/milestones/${JDTLS_VERSION}/jdt-language-server-${JDTLS_VERSION}-${JDTLS_TIMESTAMP}.tar.gz > jdtls.tar.gz && \
  mkdir /jdtls && \
  tar --extract --gzip --file jdtls.tar.gz --directory /jdtls --no-same-owner && \
  rm jdtls.tar.gz
