# Image for Java development with GraalVM and Maven
# Based on the official image available at https://hub.docker.com/_/maven

FROM docker.io/library/maven:3-eclipse-temurin-17

# Install GraalVM
ENV JAVA_VERSION=17
ENV GRAALVM_VERSION=22.3.1
RUN curl -L https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${GRAALVM_VERSION}/graalvm-ce-java${JAVA_VERSION}-linux-amd64-${GRAALVM_VERSION}.tar.gz > graalvm.tar.gz && \
  tar --extract --gzip --file graalvm.tar.gz --directory / && \
  rm graalvm.tar.gz

ENV JAVA_HOME="/graalvm-ce-java${JAVA_VERSION}-${GRAALVM_VERSION}"
ENV PATH="${JAVA_HOME}/bin:$PATH"

# Install native-image
RUN gu install native-image

# Install Java language server
ENV JDTLS_VERSION=1.19.0
ENV JDTLS_TIMESTAMP=202301171536
RUN curl -L https://download.eclipse.org/jdtls/milestones/${JDTLS_VERSION}/jdt-language-server-${JDTLS_VERSION}-${JDTLS_TIMESTAMP}.tar.gz > jdtls.tar.gz && \
  mkdir /jdtls && \
  tar --extract --gzip --file jdtls.tar.gz --directory /jdtls --no-same-owner && \
  rm jdtls.tar.gz
