# Image for Crystal development
# Based on the official image available at https://hub.docker.com/r/crystallang/crystal

# hadolint ignore=DL3007
FROM docker.io/crystallang/crystal:latest-alpine

# hadolint ignore=DL3008
RUN apk add --update --no-cache wget && \
    wget --progress=dot:giga https://github.com/elbywan/crystalline/releases/latest/download/crystalline_x86_64-unknown-linux-musl.gz -O crystalline.gz && \
    gzip -d crystalline.gz && \
    mv crystalline /usr/local/bin/crystalline && \
    chmod u+x /usr/local/bin/crystalline && \
    apk del wget
