# Image for Elixir development
# Based on the official image available at https://hub.docker.com/_/elixir

FROM docker.io/library/elixir:1.12

ENV ELIXIR_VERSION=1.12
ENV ERLANG_VERSION=24.3
ENV ELIXIR_LS_VERSION=0.12.0
RUN wget https://github.com/elixir-lsp/elixir-ls/releases/download/v${ELIXIR_LS_VERSION}/elixir-ls-${ELIXIR_VERSION}-${ERLANG_VERSION}.zip -O elixir-ls.zip && \
    mkdir --parents /opt/elixir/ls && \
    unzip elixir-ls.zip -d /opt/elixir/ls
