# Image for Erlang development
# Based on the official image available at https://hub.docker.com/_/erlang

FROM docker.io/library/erlang:24

RUN git clone https://github.com/erlang-ls/erlang_ls.git && \
    cd /erlang_ls && \
    make && \
    make install && \
    rm -rf /erlang_ls
