# Image for Julia development
# Based on the official image available at https://hub.docker.com/_/julia

FROM docker.io/library/julia:latest

RUN julia --eval 'using Pkg; Pkg.add("LanguageServer")'

# TODO: install https://github.com/julia-vscode/LanguageServer.jl
