# Image for Java development with GraalVM
# Based on the official image available at https://github.com/graalvm/container

FROM ghcr.io/graalvm/graalvm-community:22

# Install Java language server
ENV JDTLS_VERSION=1.35.0
ENV JDTLS_TIMESTAMP=202404251256
RUN curl --location --silent https://download.eclipse.org/jdtls/milestones/${JDTLS_VERSION}/jdt-language-server-${JDTLS_VERSION}-${JDTLS_TIMESTAMP}.tar.gz --output jdtls.tar.gz && \
    mkdir /jdtls && \
    tar --extract --gzip --file jdtls.tar.gz --directory /jdtls --no-same-owner && \
    rm jdtls.tar.gz

# Install Maven
ENV MAVEN_HOME /usr/share/maven

COPY --from=maven:3-eclipse-temurin-11 ${MAVEN_HOME} ${MAVEN_HOME}
COPY --from=maven:3-eclipse-temurin-11 /usr/local/bin/mvn-entrypoint.sh /usr/local/bin/mvn-entrypoint.sh
COPY --from=maven:3-eclipse-temurin-11 /usr/share/maven/ref/settings-docker.xml /usr/share/maven/ref/settings-docker.xml

RUN ln -s ${MAVEN_HOME}/bin/mvn /usr/bin/mvn

ENV MAVEN_CONFIG "/root/.m2"

ENTRYPOINT ["/usr/local/bin/mvn-entrypoint.sh"]
CMD ["mvn"]
