# Image for Rust development
# Based on the official image available at https://hub.docker.com/_/rust

FROM docker.io/library/rust:latest

RUN rustup component add rust-src && \
    mkdir -p ~/.local/bin && \
    curl --silent --location https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | \
      gunzip -c - > ~/.local/bin/rust-analyzer && \
    chmod +x ~/.local/bin/rust-analyzer
