# Image for NodeJS development
# Based on the official image available at https://hub.docker.com/_/node

# hadolint ignore=DL3007
FROM docker.io/library/node:latest

RUN npm install -g typescript-language-server typescript
