# Image for R development
# Based on the official image available at https://hub.docker.com/_/r-base

# hadolint ignore=DL3007
FROM docker.io/library/r-base:latest

RUN R -e 'install.packages("languageserver")'
